# Generates the SparseIR.jl reference fixture of `basis_max_size.rs` (issue #285):
# size, accuracy and default tau, Matsubara and omega sampling points of
# `FiniteTempBasis(statistics, β, ωmax, ε; kernel, max_size)`.
#
# Reference implementation: SparseIR.jl 1.1.4 (the native Julia implementation,
# not the libsparseir wrapper), run with Julia 1.12.5 and Float64 output.
# Usage, in an environment with SparseIR.jl 1.1.4:
#
#     julia --project=<env> basis_max_size_reference.jl > fixture.rs
#
# then replace the generated block of `basis_max_size.rs` with the output.
#
# The SVE is computed once per group with `SVEResult(kernel; ε)` and passed as
# `sve_result`. That is the default argument of `FiniteTempBasis`, so each basis
# is exactly `FiniteTempBasis(statistics, β, ωmax, ε; kernel, max_size)`: the
# SVE is not truncated, only the basis is (SparseIR.jl src/basis.jl).
using SparseIR

pkgversion(SparseIR) == v"1.1.4" || error("expected SparseIR.jl 1.1.4, got $(pkgversion(SparseIR))")

rs(x::Float64) = repr(x)

# Print `prefix`, the Rust slice literal `&[...]` of `v` and `suffix`, on one
# line if it fits in 100 columns, otherwise with the elements wrapped at 100
# columns and indented by 4 more spaces than `prefix` (the generated items carry
# #[rustfmt::skip]).
function print_slice(prefix, v, suffix)
    items = [x isa Float64 ? rs(x) : string(x) for x in v]
    oneline = prefix * "&[" * join(items, ", ") * "]" * suffix
    if length(oneline) <= 100
        println(oneline)
        return
    end
    outer = length(prefix) - length(lstrip(prefix))
    indent = outer + 4
    lines = String[]
    line = ""
    for item in items
        candidate = isempty(line) ? item * "," : line * " " * item * ","
        if indent + length(candidate) > 100 && !isempty(line)
            push!(lines, line)
            line = item * ","
        else
            line = candidate
        end
    end
    isempty(line) || push!(lines, line)
    println(prefix, "&[")
    foreach(l -> println(" "^indent, l), lines)
    println(" "^outer, "]", suffix)
end

matsus(b, positive_only) = [Int(w.n) for w in SparseIR.default_matsubara_sampling_points(b; positive_only)]

# (constant name, Rust kernel variant, kernel, β, ε, max_size values, statistics, emit tau/omega)
# Tau and omega points are emitted only for groups whose SVE runs in extended
# precision (ε below √eps(Float64)); see the tolerances in basis_max_size.rs.
groups = [
    ("LOGISTIC_LAMBDA_10", "Logistic", LogisticKernel(10.0), 10.0, 1e-10,
        [5, 6, 7, 8, 9, 10, 13], (Fermionic(), Bosonic()), true),
    ("LOGISTIC_LAMBDA_100", "Logistic", LogisticKernel(100.0), 10.0, 1e-10,
        [7, 10, 15, 20, 25], (Fermionic(), Bosonic()), true),
    ("LOGISTIC_LAMBDA_100_EPS_1E_6", "Logistic", LogisticKernel(100.0), 10.0, 1e-6,
        [7, 10, 15], (Fermionic(), Bosonic()), false),
    ("LOGISTIC_LAMBDA_1000", "Logistic", LogisticKernel(1000.0), 100.0, 1e-10,
        [20, 40], (Fermionic(), Bosonic()), true),
    ("REGULARIZED_BOSE_LAMBDA_10", "RegularizedBose", RegularizedBoseKernel(10.0), 10.0, 1e-10,
        [7, 10], (Bosonic(),), true),
]

println("// ---- BEGIN GENERATED by basis_max_size_reference.jl (SparseIR.jl ",
    pkgversion(SparseIR), ", Julia ", VERSION, ") ----")
for (name, kind, kernel, β, ε, sizes, stats, points) in groups
    ωmax = SparseIR.Λ(kernel) / β
    sve = SparseIR.SVEResult(kernel; ε)
    println("#[rustfmt::skip]")
    println("const $name: Group = Group {")
    println("    kernel: KernelKind::$kind,")
    println("    lambda: $(rs(SparseIR.Λ(kernel))),")
    println("    beta: $(rs(β)),")
    println("    eps: $(rs(ε)),")
    println("    cases: &[")
    for max_size in sizes
        bases = Dict(s => FiniteTempBasis(s, β, ωmax, ε; kernel, sve_result=sve, max_size)
                     for s in stats)
        b = bases[first(stats)]
        # Size, accuracy and the tau/omega points depend on the SVE only.
        for bs in values(bases)
            @assert length(bs) == length(b) && SparseIR.accuracy(bs) == SparseIR.accuracy(b)
            @assert SparseIR.default_tau_sampling_points(bs) == SparseIR.default_tau_sampling_points(b)
            @assert SparseIR.default_omega_sampling_points(bs) == SparseIR.default_omega_sampling_points(b)
        end
        println("        SizeCase {")
        println("            max_size: $max_size,")
        println("            size: $(length(b)),")
        println("            accuracy: $(rs(SparseIR.accuracy(b))),")
        if points
            print_slice("            tau: Some(", sort(SparseIR.default_tau_sampling_points(b)), "),")
            print_slice("            omega: Some(", sort(SparseIR.default_omega_sampling_points(b)), "),")
        else
            println("            tau: None,")
            println("            omega: None,")
        end
        for (field, S) in (("fermionic", Fermionic()), ("bosonic", Bosonic()))
            if haskey(bases, S)
                bs = bases[S]
                println("            $field: Some(Matsu {")
                print_slice("                all: ", matsus(bs, false), ",")
                print_slice("                positive: ", matsus(bs, true), ",")
                println("            }),")
            else
                println("            $field: None,")
            end
        end
        println("        },")
    end
    println("    ],")
    println("};")
end
println("// ---- END GENERATED ----")
