#!/usr/bin/env python3
"""
Setup script to prepare the build environment.

NOTE: This script is deprecated for Rust builds. The Rust library (sparse-ir-capi)
is built automatically during the CMake build process, and the header file is
auto-generated by cbindgen in sparse-ir-capi/include/sparseir/sparseir.h.

This script is kept for backward compatibility but is no longer needed.
"""

import os
import sys

def setup_build_environment():
    """Setup build environment (deprecated for Rust builds)."""
    print("WARNING: setup_build.py is deprecated for Rust builds.")
    print("The Rust library is built automatically during the CMake build process.")
    print("No file copying is needed.")
    print("")
    print("If you need to regenerate ctypes_autogen.py, run:")
    print("  python tools/gen_ctypes.py")
    print("")
    print("The header file is located at:")
    print("  ../sparse-ir-capi/include/sparseir/sparseir.h")
    print("(auto-generated by cbindgen during Rust build)")

if __name__ == "__main__":
    setup_build_environment()
