{% set name = "pylibsparseir" %}
# Match version in [workspace.package] section
{% set version = load_file_regex(
  load_file="../../Cargo.toml",
  # Capture only the package version line, ignoring rust-version
  regex_pattern="(?m)\\[workspace\\.package\\][\\s\\S]*?^version\\s*=\\s*\"([^\"]+)\"",
  from_recipe_dir=True
) .group(1) %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../..

build:
  number: 0
  script: |
    # Clean up old shared libraries
    echo "Cleaning up old shared libraries..."
    find ${SRC_DIR}/python/pylibsparseir -name "*.dylib" -o -name "*.so*" | xargs rm -f || true

    # Build the Rust sparse-ir-capi library
    echo "Building Rust sparse-ir-capi library..."
    cd ${SRC_DIR}/sparse-ir-capi
    cargo build --release

    # Build and install the Python package
    cd ${SRC_DIR}/python
    ${PYTHON} -m pip install . --no-deps --ignore-installed -v

    # Run tests during build
    #echo "Running tests..."
    #${PYTHON} -m pytest ${SRC_DIR}/python/tests -v

    # Verify what was installed
    echo "Python package contents:"
    find ${SP_DIR}/pylibsparseir -name "*" -type f

    # Final verification
    echo "Python package files:"
    find ${SP_DIR}/pylibsparseir -name "*" -type f
  files:
    - lib/python3.*/site-packages/pylibsparseir/
    - lib/python3.*/site-packages/pylibsparseir-*.egg-info/

requirements:
  build:
    - python {{ python }}
    - numpy {{ numpy }}
    - rust
  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - scipy
    - pytest
    - pip
    - hatchling >=1.21.0
  run:
    - python {{ python }}
    - numpy {{ numpy }}
    - scipy
  test:
    - pytest

test:
  imports:
    - pylibsparseir
  commands:
    - python -c "import pylibsparseir; print('pylibsparseir imported successfully')"

about:
  home: "https://github.com/SpM-lab/sparse-ir-rs"
  license: MIT
  license_file: LICENSE
  summary: Python bindings for the sparse-ir-capi library, providing efficient sparse intermediate representation for many-body physics calculations
  description: |
    pylibsparseir provides Python bindings for the sparse-ir-capi Rust library,
    enabling efficient computation of sparse intermediate representation (IR)
    basis functions used in many-body physics calculations. It provides
    efficient computation of Green's functions and other physical quantities.
  doc_url: https://github.com/SpM-lab/sparse-ir-rs
  dev_url: https://github.com/SpM-lab/sparse-ir-rs

extra:
  recipe-maintainers:
    - SpM-lab
